logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 192.168.114.128
    port: 5672
    virtual-host: /hmall  #虚拟主机名称
    username: hmall     #用户名
    password: 123        #密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，需要处理完成在处理下一条
        acknowledge-mode: auto
        retry:
          enabled: true  #消费者重试机制